image: python:3.7-slim-buster

services:
  - postgres:12.2-alpine

variables:
  POSTGRES_DB: have_i
  POSTGRES_USER: been
  POSTGRES_PASSWORD: p4wn3d
  FLASK_ENV: testing

before_script:
  - apt update
  - apt install -y postgresql-client
  - pip install .
  - pip install pytest
  - export PGPASSWORD=$POSTGRES_PASSWORD
  - psql -h "postgres" -U "$POSTGRES_USER" -d "$POSTGRES_DB" < data/scheme.sql
  

test:
  script: pytest --verbose

after_script: