before_script:
  - apt update
  - apt install git -y
  - pip install .[tests]

test:
  image: $IMAGE
  parallel:
    matrix:
      - IMAGE: ['python:3.8-slim', 'python:3.9-slim', 'python:3.10-slim', 'python:3.11-slim']
  script: 
    - pytest --verbose
