image: python:3.7-slim-buster

services:
  - timescale/timescaledb:latest-pg12

variables:
  POSTGRES_DB: sentient
  POSTGRES_USER: sview-user
  POSTGRES_PASSWORD: p4wn3d

before_script:
  - apt update
  - apt install -y postgresql-client git
  - pip install .
  - pip install pytest
  - export PGPASSWORD=$POSTGRES_PASSWORD
  - export FLASK_APP_SETTINGS=$CI_PROJECT_DIR/tests/testconfig.cfg
  - psql -h "timescale-timescaledb" -U "$POSTGRES_USER" -d "$POSTGRES_DB" < sview/statistics/scheme.sql
  - psql -h "timescale-timescaledb" -U "$POSTGRES_USER" -d "$POSTGRES_DB" < sview/statistics/testdata.sql

test:
  script: pytest --verbose

after_script: